# -*- coding: utf-8 -*-
__author__ = 'Brice Olivier'

X_COL = 'X'
Y_COL = 'Y'
SUBJECT_COL = 'SUBJ_NAME'
TEXT_NAME_COL = 'TEXT'
FIXATION_DURATION_COL = 'FDUR'

COLOR_LIGHTNESS = 60
COLOR_SATURATION = 65

RADIUS_SCALE = .1
LINE_WIDTH = 2
FONT_SIZE = 15
